require('./average');
require('./flat');
require('./asc');
require('./desc');
require('./randomize');
require('./first');
require('./last');
require('./drop');
require('./sum');
require('./copy');
require('./insert');
require('./update');
require('./shuffle');
require('./replace');
require('./replaceAll');
module.exports = {};